### ISSUE TITLE
ImageNet Pretrain

### ISSUE THREAD

**Issue by Dadatata-JZ** [sagizty/Multi-Stage-Hybrid-Transformer#1]
Hi there, 

Thank you so much for sharing this great work. Can you also share the pre-trained model/weights on ImageNet-1k? I feel it would be very useful for applying transfer learning and adapting this method. 

Cheers,

**Comment by sagizty** [comment]
Thanks for your interest in our work. Due to the agreement with the cooperate institute, all model weights are considered private data. However, the pre-trained MSHT model on ImageNet-1k can have its weight available along with the final publication update. A thousand thank goes to your attention, and the further update will be here on the MSHT official page.

**Comment by sagizty** [comment]
* Pre-trained model weight on ImageNet-1k:
https://drive.google.com/file/d/1FRQibtwi48LQRVxV7VKoEKjfWBCGUmhd/view?usp=sharing
